spring:
  profiles:
    active: dev
    include:
      - core
      - db
      - default
server:
  port: 9000

---
spring:
  profiles: default
  application:
    name: api


project:
  properties:
    angular-path: ''
    swagger-host: ''