package com.clone.chat.code;

public enum MsgCode {

	SUCCESS,
	ERROR_NULL_POINTER_EXCEPTION,
	ERROR_IO_EXCEPTION,
	ERROR_DUPLICATED_ID,
	ERROR_NOSUCHELEMENTEXCEPTION,
	ERROR_UNKNOWN,
	//..에러 유형에 따라 추가
	
}
